{
"providerUrl":"${providerUrl}",
"authUser":"${authUser}",
"authPass":"${authPass}",
"vmName":"${vmName}",
"snapshotName":"${snapshotName}",
"hostName":"${hostName}",
"suppressPowerOn":${suppressPowerOn?c}
}